from os import system
from py.ligatools import *

def welcomeMenu():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│       Welcome to the Soccer Player View App    │")
    print("│                                                │")
    print("│       ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    │")
    print("│                                                │")
    print("│        This is the login menu. You will        │")
    print("│                                                │")
    print("│        need to type a valid email format       │")
    print("│                                                │")
    print("│           in order to access the App.          │")
    print("│                                                │")
    print("│        You will have 3 chances to log in.      │")
    print("│                                                │")
    print("│                   Good luck!                   │")
    print("└────────────────────────────────────────────────┘")
    #pressAnyKey()
    
def mainMenu():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│       La Liga (The Spain Soccer Teams)         │")
    print("│                                                │")
    print("│      ─────────────────────────────────         │")
    print("│                                                │")
    print("│        l - La Liga Menu                        │")
    print("│                                                │")
    print("│        r - Real Madrid Menu                    │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("│                                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def menuLiga():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│           --  La Liga Menu --                  │")
    print("│                                                │")
    print("│        p - Positions table                     │")
    print("│                                                │")
    print("│        c - Teams with more corners             │")
    print("│                                                │")
    print("│        s - Teams with more shots               │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def menuRM():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│        --  Real Madrid Menu --                 │")
    print("│                                                │")
    print("│        p - List of players                     │")
    print("│                                                │")
    print("│        o - Oldest players                      │")
    print("│                                                │")
    print("│        n - Players by nation                   │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def menuGoodBye():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│                                                │")
    print("│              Good bye...!                      │")
    print("│                                                │")
    print("│                                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def positionsTableHeader():
    system("cls")
    print("┌─────────────────────────────────────────────────────┐")
    print("│Position Team            Matches Wins Draws Loses Pts│")
    print("└─────────────────────────────────────────────────────┘")    