from os import system

def welcomeMenu():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│       Welcome to the Spain Soccer League       │")
    print("│                                                │")
    print("│     ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░    │")
    print("│                                                │")
    print("│     In this app you will find some data and    │")
    print("│                                                │")
    print("│     analysis of the Spain soccer league and    │")
    print("│                                                │")
    print("│     Real Madrd soccer team as well. You can    │")
    print("│                                                │")
    print("│     also find unit converter and string        │")
    print("│                                                │")
    print("│     operation mudules.                         │")
    print("│                                                │")
    print("│                  Good luck!                    │")
    print("│                                                │")
    print("└────────────────────────────────────────────────┘")
    
def mainMenu():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│       La Liga (The Spain Soccer Teams)         │")
    print("│                                                │")
    print("│      ─────────────────────────────────         │")
    print("│                                                │")
    print("│        l - La Liga Menu                        │")
    print("│                                                │")
    print("│        r - Real Madrid Menu                    │")
    print("│                                                │")
    print("│        c - Converter Menu                      │")
    print("│                                                │")
    print("│        u - Utilities Menu                      │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("│                                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def menuLiga():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│           --  La Liga Menu --                  │")
    print("│                                                │")
    print("│        p - Positions table                     │")
    print("│                                                │")
    print("│        s - Teams with more shots               │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def menuRM():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│        --  Real Madrid Menu --                 │")
    print("│                                                │")
    print("│        p - List of players                     │")
    print("│                                                │")
    print("│        o - Oldest players                      │")
    print("│                                                │")
    print("│        n - Players by nation                   │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def menuGoodBye():
    system("cls")
    print("┌────────────────────────────────────────────────┐")
    print("│                                                │")
    print("│                                                │")
    print("│              Good bye...!                      │")
    print("│                                                │")
    print("│                                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
def positionsTableHeader():
    system("cls")
    print("                  Spain League Teams")
    print("┌─────────────────────────────────────────────────────┐")
    print("│Position Team            Matches Wins Draws Loses Pts│")
    print("└─────────────────────────────────────────────────────┘")    

def moreShotsHeader():
    system("cls")
    print("Teams with more shots")
    print("┌─────────────────────┐")
    print("│Team            Shots│")
    print("└─────────────────────┘")    

def listPlayersHeader():
    system("cls")
    print("     Real Madrid players")
    print("┌────────────────────────────┐")
    print("│Player            Nation Age│")
    print("└────────────────────────────┘")    

def sortByAgeHeader():
    system("cls")
    print("    Oldest players")
    print("┌─────────────────────┐")
    print("│Player            Age│")
    print("└─────────────────────┘")    

def groupNationHeader():
    system("cls")
    print("Group by nations")
    print("┌───────────────┐")
    print("│Nation    Count│")
    print("└───────────────┘")    

def convertMenu():
    system("cls")
    print("                Converter Menu")
    print("┌────────────────────────────────────────────────┐")
    print("│              From a number typed,              │")
    print("│        the converter will show you the         │")
    print("│            corresponding values of:            │")
    print("│                                                │")
    print("│            * Fahrenheit to celsius             │")
    print("│            * Miles to kilometers               │")
    print("│            * Feet to meters                    │")
    print("│            * Meters to centimeters             │")
    print("│                                                │")
    print("│                                   x to Exit    │")
    print("└────────────────────────────────────────────────┘")
    
def doConvertPrintHeader():
    system("cls")
    print(" These are the convertions for your number")
    print("───────────────────────────────────────────")
    print("")
    
def utilitiesMenu():
    system("cls")
    print("               Utilities Menu  ")
    print("┌────────────────────────────────────────────────┐")
    print("│  In this menu we'll read data from SQL Server  │")
    print("│  and we'll do some string operations over a    │")
    print("│  player name selected.                         │")
    print("│                                                │")
    print("│        s - Select a player name                │")
    print("│                                                │")
    print("│        x - Exit                                │")
    print("└────────────────────────────────────────────────┘")
    print("")
    
